AllCops:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'config/**/*.rb'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'lib/**/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'Gemfile'
    - 'Capfile'
  DisplayCopNames: true
  StyleGuideCopsOnly: true
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 110
Metrics/MethodLength:
  Max: 30
Lint/AmbiguousBlockAssociation:
  Enabled: false
Performance/HashEachMethods:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Lint/RescueWithoutErrorClass:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/MethodMissing:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - '$redis'
