language: ruby
rvm:
  - 2.4.0
env:
  - DB=postgresql
  - secure: "aUlUyNmGA95QBTTkiVnMiRfdCrKjEKlRpF2QxozwNMACS64Dxt/nGGZPPxJZCO4+qOdHWFjlgg9Rn9i++VrNNtcIOgUh7C+2Atxxd1Gv6KDXN6nyzmr2KyeVPSncbU+ru5aCL81tdkPewF4TAh5UxsPwbD/GGBfLUw3JaRLv85+fHbAqLZEoZfuJOrH0PfF/BublgbYMrlC35i7TsUmr/sY267leHaH8Yli6DEHyIKqiY7tt+vVlop3ry4SxuvCWhgivu3/u+PSTHN1VxhlFO07aiPcoTF2Zq+Pu/riT8zkVZgCXpgXCSB8B6fa+eu4f/UacwW7M/gP5zyYWTn76B2HdNuKAwDvxbxD/1v5hS7JwJpKA83YLKmhYQgEn3ITFBA4DxSQy51EcYdsznU9lMdmgIfVaInB9SSaV3RMbNrhMNtcDKErSl/HNtqqS2o4CeXifPlbiidSN7Zn9cxKg+wUpl9twIC96Zn8t8cqYqBPnNL7UeXLDWVx7HD39GbpKFSO28EEHSFBMThk4ASEDOQScDsr8NbOc8Pjvt08KlKy+DaF/NE1MEdN1CyX2AM2dHqODP82o4/QS+E0co/pBY1TkOnbdkRtjxFuv2jpPVfQ7zmxPZ37HajoBwWGaTzzPJwnheCJZL2hVAun/x5jm0ZfDR9Qg+3UlM1h3WlgV8T4="
  - secure: "M6RFZP+kv7FH1BNk3zntquJaRLEX7JCfUqu/GvB/A9QSvwjnU5rJf3AIHdHf/GFj/EVh2EYManANQPHmlk09mwoo4tJcwrztYLIxZ+jVrz7w7OdAxs8li3HEmTl77/EVV+WxFeq3/aG6OixuC6+gInpwjhyXBXXGySGBB0NUmN0ZjoJ7p3mbhMwWs00sZSevcpr03krJP924FSQkBKIMoIXS7NieW7vV85c+Ex6Z/t5qQ6wpxo1TYMuwPKo2CVPYQcLckQvR11gVOkDr0/vmvUyce4l/XJRe2y6/sVbeULXwYVf3aymlrRw7h8ZJyqnxTQRl0u+2U4wKT4rD9Lc4WbUW+vJ2HE/VaFhTRM2FOKO3sMgXGCO6Yphxr2+kEFFsny3iJwY3AGmMJNmh1m1YNV6/mFf7qLp2YNki3SVLEoCqDojEHa7xAyJGZK4jsiBskF8zcixWwPEJQzFF92M4ktOcQAmS3aSun9qVb846+JIeNa7QTjyUzWFt1kFrFNT7OH5O2A3l5Aly4MhZD3WAk5hHbbIjrRn7DyAsRy1/l7cxm/LTulQaJROG1sdOQnDkPXBjBVpRf7e59j/+wh6mt1y4cIweannbMhVviVz8n3l5YbA5VRQITZLU/TZJLOzez/a4AgRN0hC7SBKBWJpzXjSARkLZS/0v34rjZfoDHac="
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_script:
  - psql -c 'create database flashcards_test' -U postgres
  - cp config/database.travis.yml config/database.yml
