language: ruby
rvm:
  - 2.4.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_script:
  - psql -c 'create database flashcards_test' -U postgres
  - cp config/database.travis.yml config/database.yml
env:
  - secure: "3Vqx2ZBj88hWesSTr9XAGuNZsASHSSKP9XmwciXFEEeHz9x2J6mC+zPLClZGhLnyGSi3IykrqrS1dbTHYNoR0V+lcNlGSfRRgFy2ks8yj4CULiHNzUwaDk2GHi3mn2fMLlCPtLlaEWYL7/gh4SYwN5mCF+extJZYFO+jvXFmQegAJuXzluQMTDqbYFPK/+z9JrcaIS8FeXMkkoFZCLyM+deGPKDVw7IIZKqD6lTyHAStjFqz97Sdp365Bl0ogsrAzE2XujAnDb1iYRejaPlU0Cp7ei/EA4lHavFTf/3745WoqK3VPRPlM5eyPV6ttWux1cjBvElZvIFPHSmwcXRCq74kWQmMY+6XOWN2eKm/Go2KOiLyevt4wDE0Ps09cG6pe0+ag5DOOQnv2yOWuqyclRgN+66mkeQ02iX9uEOKomIvAxDWRJjFD8DYr8k8zd/Prpa9wBKYNEsh6j4jU32VlXgXbcuavD9NqDqz0E+bjrm6+D6yNbbEPwtiORYS81xNy9CsOxoVoP8VPSx/BG4QQTCy8IVv2k73rll6584QdLEsviV513scLy3DOE1TkGKFeKnfzXQiIDbNnvjGfNwzh0cYI1jMMmfqyVsaJqRDDYjZ2+k/WLmPwIJn5HNu+XpLV81N/r6hsFsCSDJjJWBX8S/7sj7gqAWpQ/AaL2XpSls="
  - secure: "TVQSWKFz/ttcsRv+45vj+PTx1Oh3CtKdtPmGfc/RvuhtzYl4/VnEuZs83FYKgGUEbaUTeoU1SK0fNHCwY4yyg4PU9ErvyXL5cc5vYgnqIEqV0qnESOHmCd4iU5IOZxapQMQ5tmy0Vjn93QGw1ssupdcVnshF2Ny3UQOEJ0xgm/+N78c0ZKNwMWdDbZDi1fbdyBBFpIpw8QPmemOJVKm1SI+rW+k1jQC4KqY7GSB0jIZ24qkRlratv88Uvlbq36PaWoiO/gUddOvuUGFCc9rx7Da3Pxs6XrVkkphpp7ls1lbOi4oDO3w4+GFfwsgDUCucR6cY9xclb8Kl+ISL+9P5Y9ppxv39kW0o9mziCWd7x1fq9Uwzsm5bu3EeS3ySgqu3+RaGnzOkbj6F9XRbIICymQV+pfPgMsQ6oGpOHQwuwvaY7I32TSOpPBlNG68NCTnFTaHXW3fKlw6t0aFt0JjRBz8bmgZPxcr8cEnjUlneoUFLjy4kcrKlwj/gArErt6bAPBAhnHLn3SsX+hhMEfWqCqjnLAJ40R1fwR1087C7N138vH55vussYhoHXHiWwhu23pl3WZ+3WfVaWV+E9WyWXikZ8tzRD6eOCoNd4HxVm4eX6XSftDKQaFC5zD7mIOx0TvlSjwvBeIuVcGHz/ucZse6dtZjmCl2tbIgyKtCZAps="
